### ISSUE TITLE
Errors in MainMenu.java

### ISSUE THREAD

**Issue by raymonduong108** [introtocomputerscience/JavaBankApp#6]
Errors on line 39, 269,274,277

![error1](https://cloud.githubusercontent.com/assets/16198314/20826697/73bf7822-b832-11e6-972e-d063526f299a.PNG)

![error2](https://cloud.githubusercontent.com/assets/16198314/20826713/8d272170-b832-11e6-92e3-b7afb27e2be4.PNG)

**Comment by rawrspace** [comment]
Thanks for finding this issue. It appears it was introduced when the DefaultTableModel code was refactored in one of the most recent pull requests. The variable name was intended to be accountTable but the developer simply put table and I did not catch it in the code review.

![error-fix-1](https://cloud.githubusercontent.com/assets/5750739/20835409/17611346-b860-11e6-9f39-274b2338bdb9.png)

![error-fix-2](https://cloud.githubusercontent.com/assets/5750739/20835411/1b87ac1e-b860-11e6-8b41-1870ea96ae3e.png)

Please let me know if you find any other issues.
